---
name: Publish npm package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Download release files
        run: gh release download $GITHUB_REF_NAME --pattern=release.zip

      - name: Extract release files
        run: unzip release.zip

      - name: Publish on npm
        run: |
          cd release
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
...
