---
name: Validate feature

on:
  push:
    branches:
      - 'build/*'
      - 'chore/*'
      - 'ci/*'
      - 'docs/*'
      - 'feat/*'
      - 'fix/*'
      - 'perf/*'
      - 'refactor/*'
      - 'revert/*'
      - 'style/*'
      - 'test/*'
    tags:
      - '*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Prettier
        run: yarn prettier --check .

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn run lint @gouvfr-anct/mediation-numerique

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build @gouvfr-anct/mediation-numerique

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn run test @gouvfr-anct/mediation-numerique

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [prettier, lint, test, build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Add license file
        run: mv LICENSE.md dist/@gouvfr-anct/mediation-numerique/

      - name: Zip release
        run: zip -r release.zip dist/@gouvfr-anct/mediation-numerique/

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: https://registry.npmjs.org
          scope: '@gouvfr-anct'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: release

      - name: Publish on npm
        run: |
          cd release/@gouvfr-anct/mediation-numerique/
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
...
