---
name: Validate feature

on:
  push:
    branches:
      - 'build/*'
      - 'chore/*'
      - 'ci/*'
      - 'docs/*'
      - 'feat/*'
      - 'fix/*'
      - 'perf/*'
      - 'refactor/*'
      - 'revert/*'
      - 'style/*'
      - 'test/*'
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Prettier
        run: yarn prettier --check .

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint @gouvfr-anct/mediation-numerique

  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: commitlint
        run: |
          cd projects/@gouvfr-anct/mediation-numerique/
          npx commitlint --from origin/main

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build @gouvfr-anct/mediation-numerique

      - name: Add license and style files
        run: |
          mv projects/@gouvfr-anct/mediation-numerique/LICENSE.md dist/@gouvfr-anct/mediation-numerique/
          mv projects/@gouvfr-anct/mediation-numerique/assets/scss dist/@gouvfr-anct/mediation-numerique/

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout mediation-numerique library repository
        uses: actions/checkout@v3
        with:
          path: projects/@gouvfr-anct/mediation-numerique

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Install dependencies
        run: |
          yarn
          yarn global add @angular/cli

      - name: Test
        run: |
          cd projects/@gouvfr-anct/mediation-numerique
          ng test @gouvfr-anct/mediation-numerique
